version: "3.8"
services:
  elasticsearch:
    container_name: es-container-bella
    image: docker.elastic.co/elasticsearch/elasticsearch:8.6.0
    environment:
      - xpack.security.enabled=false
      - 'discovery.type=single-node'
    networks:
      - es-net
    ports:
      - '9292:9200'
  kibana:
    container_name: kb-container-bella
    image: docker.elastic.co/kibana/kibana:8.6.0
    environment:
      - ELASTICSEARCH_HOSTS=http://es-container-bella:9200
    networks:
      - es-net
    depends_on:
      - elasticsearch
    ports:
      - '5656:5601'
  pg:
    container_name: postgresql-container-bella
    image: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=postgres
    ports:
      - '5454:5432'
    volumes:
      - ./data/postgres:/var/lib/postgresql/data/

networks:
  es-net:
    driver: bridge

volumes:
  db:
    driver: local