spring:
  datasource:
    url: jdbc:postgresql://localhost:5454/postgres
    username: postgres
    password: password
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
  flyway:
    init-sqls:
      - drop table if exists flyway_schema_history