springdoc:
  api-docs:
    enabled: true
    path: /open-api
    groups:
      enabled: true
  swagger-ui:
    path: /documentation

spring:
  jackson:
    default-property-inclusion: non_null
  jpa:
    open-in-view: false
  flyway:
    enabled: false
    baseline-on-migrate: true